### ISSUE TITLE
Consolidação dos Parsers (SonarCloud e GitHub) na root do repositório.

### ISSUE THREAD

**Issue by viniman27** [fga-eps-mds/Analytics#15]
Construir um arquivo de parser_template.py único que consolide as funcionalidades do parser.py presente no tutorial de SonarCloud e o parser_template.py já existente que puxa as informações de métricas do GitHub. Esse arquivo deve se fazer presente na root do repositório para acesso de todos.

**Comment by hneri** [comment]
👍🏽👍🏽 Valeu @victorleaoo e @viniman27 !!
