### ISSUE TITLE
Implementar e corrigir métricas no Notebook do GitHub.

### ISSUE THREAD

**Issue by JoaoPedro0803** [fga-eps-mds/Analytics#17]
1 → Criar a medida de throughput seguindo a orientação do documento do Q-Rapids e apresentar seu gráfico.

2 → Alterar a construção da métrica de CI Feedback, a fim de filtrar as Pipelines/Workflows apenas de build (usuário insere essa informação), já que hoje em dia pega a informação de todos os Workflows.

Além disso, um filtro de datas deve ser possível de ser aplicado por parte do usuário para visualizar as métricas em um determinado período de tempo.

**Comment by hneri** [comment]
👍🏽👍🏽 Valeu @victorleaoo e @JoaoPedro0803
