### ISSUE TITLE
Elaborar tutorial de orquestração do pipeline para coleta de métricas relacionadas a execução de testes automatizados (unitário e integração)

### ISSUE THREAD

**Issue by hneri** [fga-eps-mds/Analytics#3]
Os tutorias devem apresentar uma orientação descritiva do “how-to” para instalação, configuração e coleta de métricas e medidas relacionadas a execução dos testes automatizados em nível unitário e integração. As seguintes métricas devem ser extraídas:
- coverage 
- tests
- test_success_density
- test_execution_time

Após a extração das métricas de teste, atualizar o arquivo (.json) extraído da ferramenta Sonar via chamada a API do serviço []
[SonarCloud](https://sonarcloud.io/)
 Além disso, descrever o scprit de automação desses procedimentos nos respectivos pipelines(actions) para um projeto da disciplina. Os passos do script devem contemplar a coleta das métricas nas respectivas tecnologias e atualização do arquivo gerado pelo Sonar 
Esses tutoriais devem ser disponibilizados em:
[Tutoriais-e-Materiais](https://github.com/fga-eps-mds/A-Disciplina-MDS-EPS/wiki/Tutoriais-e-Materiais)

#### @Henrike100 
- [x] Elaborar um tutorial de configuração e orquestração da action de coleta de métricas de testes utilizando Jest
- [x] Elaborar um tutorial de configuração e orquestração da action de coleta de métricas de testes utilizando pytest
#### @GabrielTiveron 
- [x] Elaborar um tutorial de configuração e orquestração da action de coleta de métricas de testes utilizando Mocha
- [x] Elaborar um tutorial de configuração e orquestração da action de coleta de métricas de testes utilizando Istanbul

**Comment by Henrike100** [comment]
@hneri terminei os documentos, como devo proceder agora?

O senhor pediu para abrir um PR, mas tem como abrir um PR para a wiki?

**Comment by hneri** [comment]
Otimo, @Henrike100 ! Tão logo você "suba" a pagina, referencie a url aqui. Eu me confundi quanto ao PR. Caso seja necessario, eu faco alguma revisao direto na pagina. 
Alem disso, manterei a comunicacao por aqui.

**Comment by Henrike100** [comment]
@hneri subi as páginas na wiki

[Configurar o SonarCloud para um projeto usando Jest](https://github.com/fga-eps-mds/A-Disciplina-MDS-EPS/wiki/Configurar-o-SonarCloud-para-um-projeto-usando-Jest)

[Configurar o SonarCloud para um projeto usando Pytest](https://github.com/fga-eps-mds/A-Disciplina-MDS-EPS/wiki/Configurar-o-SonarCloud-para-um-projeto-usando-Pytest)

**Comment by hneri** [comment]
Excelente trabalho e contribuicao para a disciplina de EPS, @Henrike100 ! Parabens !!!

**Comment by GabrielTiveron** [comment]
@hneri subi a página para a wiki!

[Configurar o SonarCloud para um projeto usando Mocha e Istambul](https://github.com/fga-eps-mds/A-Disciplina-MDS-EPS/wiki/Configurar-o-SonarCloud-para-um-projeto-usando-Mocha-e-Istambul)

**Comment by hneri** [comment]
Excelente trabalho e contribuicao para a disciplina de EPS, @GabrielTiveron  ! Parabens !!!

**Comment by hneri** [comment]
@Henrike100 , por favor voce pode "subir" o parser que você utilizou para manipular os arquivos gerados pelo jest e pytest, como um passo adicional aos tutoriais que voce elaborou?

**Comment by Henrike100** [comment]
@hneri feito!

**Comment by hneri** [comment]
@Henrike100 e @GabrielTiveron , essa contribuição de vocês auxiliará muitos e muitas colegas em semestres futuros. Será fundamental para e extração automática, via pipeline, das métricas e medidas dos resultados da execução testes em nível unitário e integração. Mandaram muito bem!
